import Papa from 'papaparse';
import { Employee, Equipment, Material, Site, TimeLog, User, EmployeeLog, EquipmentLog, MaterialLog } from '../types';
import { CSVAppendManager } from './csvAppendUtils';
import { v4 as uuidv4 } from 'uuid';

interface Department {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
  lastUpdated: string;
}

interface TransactionLog {
  id: string;
  entityType: string;
  action: 'create' | 'update' | 'delete';
  entityId: string;
  data: unknown;
  timestamp: string;
  userId?: string;
}

// CSV Storage utilities
export class DataStorage {
  private static readonly STORAGE_KEYS = {
    employees: 'qr_system_employees',
    equipment: 'qr_system_equipment',
    materials: 'qr_system_materials',
    sites: 'qr_system_sites',
    timeLogs: 'qr_system_time_logs',
    employeeLogs: 'qr_system_employee_logs',
    equipmentLogs: 'qr_system_equipment_logs',
    materialLogs: 'qr_system_material_logs',
    maintenanceLogs: 'qr_system_maintenance_logs',
    maintenanceSchedules: 'qr_system_maintenance_schedules',
    preventiveMaintenanceConfigs: 'qr_system_preventive_maintenance_configs',
    classMaintenanceTypes: 'qr_system_class_maintenance_types',
    maintenanceMaterialRequests: 'qr_system_maintenance_material_requests',
    maintenanceMaterialRequestItems: 'qr_system_maintenance_material_request_items',
    users: 'qr_system_users',
    departments: 'qr_system_departments',
    costElements: 'qr_system_cost_elements',
    transactionLog: 'qr_system_transaction_log',
    lastSync: 'qr_system_last_sync',
    counters: 'qr_system_counters'
  };

  // Save data to localStorage as CSV
  static saveToCSV<T>(key: string, data: T[]): void {
    try {
      const csv = Papa.unparse(data);
      localStorage.setItem(key, csv);
    } catch (error) {
      console.error(`Error saving ${key} to CSV:`, error);
    }
  }

  // Load data from localStorage CSV
  static loadFromCSV<T>(key: string): T[] {
    try {
      const csv = localStorage.getItem(key);
      if (!csv) return [];
      
      const result = Papa.parse(csv, { 
        header: true,
        dynamicTyping: true,
        skipEmptyLines: true
      });
      return result.data as T[];
    } catch (error) {
      console.error(`Error loading ${key} from CSV:`, error);
      return [];
    }
  }

  // Download CSV file
  static downloadCSV(data: unknown[], filename: string): void {
    const csv = Papa.unparse(data);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  // Download CSV report data
  static downloadReportCSV(data: unknown, filename: string): void {
    // Save to Logs.csv with append functionality
    this.saveReportToLogsCSV(data);
    
    // Also download the report file for user
    this.downloadReportAsCSV(data, filename);
  }

  // Save report data to Logs.csv with append functionality
  static saveReportToLogsCSV(data: unknown): void {
    try {
      // Create log entry for this report
      const dataObj = data as Record<string, unknown>;
      const logEntry = {
        'Timestamp': new Date().toISOString(),
        'Report Type': (dataObj.reportType as string) || 'Unknown',
        'Entity Type': (dataObj.entityType as string) || 'All',
        'Date Range Start': (dataObj.dateRange as { start?: string })?.start ? new Date((dataObj.dateRange as { start?: string }).start!).toISOString() : '',
        'Date Range End': (dataObj.dateRange as { end?: string })?.end ? new Date((dataObj.dateRange as { end?: string }).end!).toISOString() : '',
        'Generated By': this.getCurrentUserId() || 'System',
        'Employee Records': dataObj.employeeHours ? Object.keys(dataObj.employeeHours as Record<string, unknown>).length : 0,
        'Equipment Records': dataObj.equipmentUsage ? Object.keys(dataObj.equipmentUsage as Record<string, unknown>).length : 0,
        'Material Records': dataObj.materialMovement ? Object.keys(dataObj.materialMovement as Record<string, unknown>).length : 0,
        'Activity Logs': dataObj.logs ? (dataObj.logs as unknown[]).length : 0,
        'Total Records': (dataObj.logs ? (dataObj.logs as unknown[]).length : 0) + 
                        (dataObj.employeeHours ? Object.keys(dataObj.employeeHours as Record<string, unknown>).length : 0) +
                        (dataObj.equipmentUsage ? Object.keys(dataObj.equipmentUsage as Record<string, unknown>).length : 0) +
                        (dataObj.materialMovement ? Object.keys(dataObj.materialMovement as Record<string, unknown>).length : 0)
      };

      // Load existing logs
      const existingLogs = this.loadLogsCSV();
      
      // Append new log entry
      existingLogs.push(logEntry);
      
      // Save back to Logs.csv
      this.saveLogsCSV(existingLogs);
      
      console.log('Report logged to Logs.csv successfully');
    } catch (error) {
      console.error('Failed to save report to Logs.csv:', error);
    }
  }

  // Load existing Logs.csv data
  static loadLogsCSV(): unknown[] {
    return this.loadFromCSV('qr_system_logs');
  }

  // Save data to Logs.csv
  static saveLogsCSV(logs: unknown[]): void {
    this.saveToCSV('qr_system_logs', logs);
  }

  // Download Logs.csv file
  static downloadLogsCSV(): void {
    const logs = this.loadLogsCSV();
    this.downloadCSV(logs, 'Logs.csv');
  }

  // Download report as separate CSV file (original functionality)
  static downloadReportAsCSV(data: unknown, filename: string): void {
    // Convert report object to CSV format
    const csvData = [];
    
    // Add report metadata
    const dataObj = data as Record<string, unknown>;
    csvData.push({
      'Report Type': (dataObj.reportType as string) || 'Unknown',
      'Entity Type': (dataObj.entityType as string) || 'All',
      'Date Range Start': (dataObj.dateRange as { start?: string })?.start ? new Date((dataObj.dateRange as { start?: string }).start!).toLocaleDateString() : '',
      'Date Range End': (dataObj.dateRange as { end?: string })?.end ? new Date((dataObj.dateRange as { end?: string }).end!).toLocaleDateString() : '',
      'Generated At': new Date().toLocaleString()
    });
    
    // Add empty row
    csvData.push({});
    
    // Add employee hours data if available
    if (dataObj.employeeHours && Object.keys(dataObj.employeeHours as Record<string, unknown>).length > 0) {
      csvData.push({ 'Section': 'Employee Hours Summary' });
      Object.entries(dataObj.employeeHours as Record<string, unknown>).forEach(([employeeId, hours]: [string, unknown]) => {
        csvData.push({
          'Employee ID': employeeId,
          'Regular Hours': hours.regular,
          'Overtime Hours': hours.overtime,
          'Total Hours': hours.total,
          'Shifts': hours.shifts
        });
      });
      csvData.push({});
    }
    
    // Add equipment usage data if available
    if (data.equipmentUsage && Object.keys(data.equipmentUsage).length > 0) {
      csvData.push({ 'Section': 'Equipment Usage Summary' });
      Object.entries(data.equipmentUsage).forEach(([equipmentId, usage]: [string, any]) => {
        csvData.push({
          'Equipment ID': equipmentId,
          'Total Hours': usage.totalHours,
          'Sessions': usage.sessions
        });
      });
      csvData.push({});
    }
    
    // Add material movement data if available
    if (data.materialMovement && Object.keys(data.materialMovement).length > 0) {
      csvData.push({ 'Section': 'Material Movement Summary' });
      Object.entries(data.materialMovement).forEach(([materialId, movement]: [string, any]) => {
        csvData.push({
          'Material ID': materialId,
          'Received': movement.received,
          'Issued': movement.issued,
          'Net Movement': movement.net
        });
      });
      csvData.push({});
    }
    
    // Add activity logs if available
    if (data.logs && data.logs.length > 0) {
      csvData.push({ 'Section': 'Activity Logs' });
      data.logs.forEach((log: any) => {
        csvData.push({
          'Log ID': log.id,
          'Entity ID': log.entityId,
          'Entity Type': log.entityType,
          'Action': log.action,
          'Timestamp': new Date(log.timestamp).toLocaleString(),
          'Site': log.site,
          'Notes': log.notes || '',
          'Quantity': log.quantity || ''
        });
      });
    }
    
    this.downloadCSV(csvData, filename);
  }

  // Employees
  static saveEmployees(employees: Employee[]): void {
    this.saveToCSV(this.STORAGE_KEYS.employees, employees);
  }

  static loadEmployees(): Employee[] {
    return this.loadFromCSV<Employee>(this.STORAGE_KEYS.employees);
  }

  static downloadEmployeesCSV(employees: Employee[]): void {
    this.downloadCSV(employees, 'employees.csv');
  }

  // Equipment
  static saveEquipment(equipment: Equipment[]): void {
    this.saveToCSV(this.STORAGE_KEYS.equipment, equipment);
  }

  static loadEquipment(): Equipment[] {
    return this.loadFromCSV<Equipment>(this.STORAGE_KEYS.equipment);
  }

  static downloadEquipmentCSV(equipment: Equipment[]): void {
    this.downloadCSV(equipment, 'equipment.csv');
  }

  // Materials
  static saveMaterials(materials: Material[]): void {
    this.saveToCSV(this.STORAGE_KEYS.materials, materials);
  }

  static loadMaterials(): Material[] {
    return this.loadFromCSV<Material>(this.STORAGE_KEYS.materials);
  }

  static downloadMaterialsCSV(materials: Material[]): void {
    this.downloadCSV(materials, 'materials.csv');
  }

  // Sites
  static saveSites(sites: Site[]): void {
    this.saveToCSV(this.STORAGE_KEYS.sites, sites);
    console.log(`Sites saved to storage: ${sites.length} sites`);
    // Log the first few sites for debugging
    if (sites.length > 0) {
      console.log("Sample site data:", JSON.stringify(sites[0]));
    }
  }

  static loadSites(): Site[] {
    const sites = this.loadFromCSV<Site>(this.STORAGE_KEYS.sites);
    console.log(`Sites loaded from storage: ${sites.length} sites`);

    // Process and fix site coordinates
    const processedSites = sites.map(site => {
      let coordinates: [number, number] = [0, 0];
      
      try {
        // Handle different coordinate formats
        if (site.coordinates) {
          // Case 1: Already an array of numbers
          if (Array.isArray(site.coordinates) && 
              typeof site.coordinates[0] === 'number' && 
              typeof site.coordinates[1] === 'number') {
            coordinates = [site.coordinates[0], site.coordinates[1]];
          }
          // Case 2: Array of strings
          else if (Array.isArray(site.coordinates)) {
            coordinates = [
              parseFloat(String(site.coordinates[0])), 
              parseFloat(String(site.coordinates[1]))
            ];
          }
          // Case 3: String in format "lng,lat"
          else if (typeof site.coordinates === 'string' && (site.coordinates as string).includes(',')) {
            const parts = (site.coordinates as string).split(',').map((part: string) => parseFloat(part.trim()));
            if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
              coordinates = [parts[0], parts[1]];
            }
          }
          // Case 4: String in format "lat lng"
          else if (typeof site.coordinates === 'string' && (site.coordinates as string).includes(' ')) {
            const parts = (site.coordinates as string).split(' ').map((part: string) => parseFloat(part.trim()));
            if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
              coordinates = [parts[1], parts[0]]; // Note: swapping to [lng, lat]
            }
          }
        }
        
        // Validate coordinates
        if (isNaN(coordinates[0]) || isNaN(coordinates[1]) ||
            coordinates[0] === 0 || coordinates[1] === 0) {
          console.warn(`Site ${site.id} has invalid coordinates, using default:`, site.coordinates);
          // Default to Riyadh coordinates
          coordinates = [46.6753, 24.7136];
        }
      } catch (error) {
        console.error(`Error processing coordinates for site ${site.id}:`, error);
        coordinates = [46.6753, 24.7136]; // Default to Riyadh
      }
      
      return {
        ...site,
        coordinates
      };
    });

    // Log coordinate processing results
    console.log(`Sites after coordinate processing: ${processedSites.length} sites`);
    if (processedSites.length > 0) {
      console.log("Sample processed site:", JSON.stringify(processedSites[0]));
    }
    
    return processedSites;
  }

  static downloadSitesCSV(sites: Site[]): void {
    this.downloadCSV(sites, 'sites.csv');
  }

  // Time Logs (Legacy - for backward compatibility)
  static saveTimeLogs(timeLogs: TimeLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.timeLogs, timeLogs);
  }

  static loadTimeLogs(): TimeLog[] {
    return this.loadFromCSV<TimeLog>(this.STORAGE_KEYS.timeLogs);
  }

  static downloadTimeLogsCSV(timeLogs: TimeLog[]): void {
    this.downloadCSV(timeLogs, 'time_logs.csv');
  }

  // Employee Logs
  static saveEmployeeLogs(employeeLogs: EmployeeLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.employeeLogs, employeeLogs);
  }

  static loadEmployeeLogs(): EmployeeLog[] {
    return this.loadFromCSV<EmployeeLog>(this.STORAGE_KEYS.employeeLogs);
  }

  static downloadEmployeeLogsCSV(employeeLogs: EmployeeLog[]): void {
    this.downloadCSV(employeeLogs, 'employee_logs.csv');
  }

  // Equipment Logs
  static saveEquipmentLogs(equipmentLogs: EquipmentLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.equipmentLogs, equipmentLogs);
  }

  static loadEquipmentLogs(): EquipmentLog[] {
    return this.loadFromCSV<EquipmentLog>(this.STORAGE_KEYS.equipmentLogs);
  }

  static downloadEquipmentLogsCSV(equipmentLogs: EquipmentLog[]): void {
    this.downloadCSV(equipmentLogs, 'equipment_logs.csv');
  }

  // Material Logs
  static saveMaterialLogs(materialLogs: MaterialLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.materialLogs, materialLogs);
  }

  static loadMaterialLogs(): MaterialLog[] {
    return this.loadFromCSV<MaterialLog>(this.STORAGE_KEYS.materialLogs);
  }

  static downloadMaterialLogsCSV(materialLogs: MaterialLog[]): void {
    this.downloadCSV(materialLogs, 'material_logs.csv');
  }

  // Maintenance Logs
  static saveMaintenanceLogs(maintenanceLogs: EquipmentMaintenanceLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.maintenanceLogs, maintenanceLogs);
  }

  static loadMaintenanceLogs(): EquipmentMaintenanceLog[] {
    return this.loadFromCSV<EquipmentMaintenanceLog>(this.STORAGE_KEYS.maintenanceLogs);
  }

  static downloadMaintenanceLogsCSV(maintenanceLogs: EquipmentMaintenanceLog[]): void {
    this.downloadCSV(maintenanceLogs, 'maintenance_logs.csv');
  }

  // Maintenance Schedules
  static saveMaintenanceSchedules(maintenanceSchedules: EquipmentMaintenanceSchedule[]): void {
    this.saveToCSV(this.STORAGE_KEYS.maintenanceSchedules, maintenanceSchedules);
  }

  static loadMaintenanceSchedules(): EquipmentMaintenanceSchedule[] {
    return this.loadFromCSV<EquipmentMaintenanceSchedule>(this.STORAGE_KEYS.maintenanceSchedules);
  }

  static downloadMaintenanceSchedulesCSV(maintenanceSchedules: EquipmentMaintenanceSchedule[]): void {
    this.downloadCSV(maintenanceSchedules, 'maintenance_schedules.csv');
  }

  // Preventive Maintenance Configuration methods
  static savePreventiveMaintenanceConfigs(configs: any[]): void {
    this.saveToCSV(this.STORAGE_KEYS.preventiveMaintenanceConfigs, configs);
  }

  static loadPreventiveMaintenanceConfigs(): any[] {
    return this.loadFromCSV(this.STORAGE_KEYS.preventiveMaintenanceConfigs);
  }

  static downloadPreventiveMaintenanceConfigsCSV(configs: any[]): void {
    this.downloadCSV(configs, 'preventive_maintenance_configs.csv');
  }

  // Class Maintenance Types
  static saveClassMaintenanceTypes(classTypes: any[]): void {
    this.saveToCSV(this.STORAGE_KEYS.classMaintenanceTypes, classTypes);
  }

  static loadClassMaintenanceTypes(): any[] {
    return this.loadFromCSV<any>(this.STORAGE_KEYS.classMaintenanceTypes);
  }

  static downloadClassMaintenanceTypesCSV(classTypes: any[]): void {
    this.downloadCSV(classTypes, 'class_maintenance_types.csv');
  }

  // Combined Logs Helper (for reports that need all logs)
  static loadAllLogs(): { employeeLogs: EmployeeLog[]; equipmentLogs: EquipmentLog[]; materialLogs: MaterialLog[] } {
    return {
      employeeLogs: this.loadEmployeeLogs(),
      equipmentLogs: this.loadEquipmentLogs(),
      materialLogs: this.loadMaterialLogs()
    };
  }

  // Users
  static saveUsers(users: User[]): void {
    this.saveToCSV(this.STORAGE_KEYS.users, users);
  }

  static loadUsers(): User[] {
    return this.loadFromCSV<User>(this.STORAGE_KEYS.users);
  }

  static downloadUsersCSV(users: User[]): void {
    this.downloadCSV(users, 'users.csv');
  }

  // Departments
  static saveDepartments(departments: Department[]): void {
    this.saveToCSV(this.STORAGE_KEYS.departments, departments);
  }

  static loadDepartments(): Department[] {
    const departments = this.loadFromCSV<Department>(this.STORAGE_KEYS.departments);
    
    // Initialize with default departments if none exist
    if (departments.length === 0) {
      const defaultDepartments: Department[] = [
        {
          id: 'dept-construction',
          name: 'Construction',
          description: 'Construction and building operations',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        },
        {
          id: 'dept-operations',
          name: 'Operations',
          description: 'Daily operations and maintenance',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        },
        {
          id: 'dept-maintenance',
          name: 'Maintenance',
          description: 'Equipment maintenance and repair services',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        },
        {
          id: 'dept-engineering',
          name: 'Engineering',
          description: 'Engineering and technical services',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        },
        {
          id: 'dept-safety',
          name: 'Safety',
          description: 'Health, safety, and environmental',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        },
        {
          id: 'dept-admin',
          name: 'Administration',
          description: 'Administrative and support services',
          createdAt: new Date().toISOString(),
          lastUpdated: new Date().toISOString()
        }
      ];
      
      this.saveDepartments(defaultDepartments);
      return defaultDepartments;
    }
    
    return departments;
  }

  // Cost Elements
  static saveCostElements(costElements: any[]): void {
    this.saveToCSV(this.STORAGE_KEYS.costElements, costElements);
  }

  static loadCostElements(): any[] {
    return this.loadFromCSV<any>(this.STORAGE_KEYS.costElements);
  }

  static downloadCostElementsCSV(costElements: any[]): void {
    this.downloadCSV(costElements, 'cost_elements.csv');
  }

  // ID Generation
  static generateEmployeeId(): string {
    // Generate UUID for employee ID (like equipment)
    return uuidv4();
  }

  static generateMaterialId(): string {
    // Generate UUID for material ID (like equipment)
    return uuidv4();
  }

  static generateSiteId(): string {
    const counters = this.getCounters();
    const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const counter = String(counters.site).padStart(3, '0');
    // Add timestamp and random component to ensure uniqueness across sessions
    const timestamp = Date.now().toString().slice(-4); // Last 4 digits of timestamp
    const random = Math.floor(Math.random() * 100).toString().padStart(2, '0');
    
    counters.site++;
    this.saveCounters(counters);
    
    return `SITE-${date}-${counter}-${timestamp}${random}`;
  }

  static generateEquipmentId(): string {
    const counters = this.getCounters();
    const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const counter = String(counters.equipment).padStart(3, '0');
    // Add timestamp and random component to ensure uniqueness across sessions
    const timestamp = Date.now().toString().slice(-4); // Last 4 digits of timestamp
    const random = Math.floor(Math.random() * 100).toString().padStart(2, '0');
    
    counters.equipment++;
    this.saveCounters(counters);
    
    return `EQP-${date}-${counter}-${timestamp}${random}`;
  }

  private static getCounters(): { employee: number; material: number; site: number; equipment: number } {
    try {
      const counters = localStorage.getItem(this.STORAGE_KEYS.counters);
      return counters ? JSON.parse(counters) : { employee: 1, material: 1, site: 1, equipment: 1 };
    } catch {
      return { employee: 1, material: 1, site: 1, equipment: 1 };
    }
  }

  private static saveCounters(counters: { employee: number; material: number; site: number; equipment: number }): void {
    localStorage.setItem(this.STORAGE_KEYS.counters, JSON.stringify(counters));
  }

  // Transaction Logging
  static logTransaction(entityType: string, action: 'create' | 'update' | 'delete', data: any): void {
    const logs = this.loadTransactionLogs();
    const newLog: TransactionLog = {
      id: `txn-${Date.now()}`,
      entityType,
      action,
      entityId: data.id,
      data,
      timestamp: new Date().toISOString(),
      userId: this.getCurrentUserId()
    };
    
    logs.push(newLog);
    this.saveTransactionLogs(logs);
  }

  private static loadTransactionLogs(): TransactionLog[] {
    return this.loadFromCSV<TransactionLog>(this.STORAGE_KEYS.transactionLog);
  }

  private static saveTransactionLogs(logs: TransactionLog[]): void {
    this.saveToCSV(this.STORAGE_KEYS.transactionLog, logs);
  }

  private static getCurrentUserId(): string | undefined {
    try {
      const userStr = localStorage.getItem('qr_system_current_user');
      const user = userStr ? JSON.parse(userStr) : null;
      return user?.id;
    } catch {
      return undefined;
    }
  }

  // Incremental Sync
  static getLastSyncTimestamp(): string | null {
    return localStorage.getItem(this.STORAGE_KEYS.lastSync);
  }

  static updateLastSyncTimestamp(): void {
    localStorage.setItem(this.STORAGE_KEYS.lastSync, new Date().toISOString());
  }

  static getModifiedRecordsSince(timestamp: string): any[] {
    const logs = this.loadTransactionLogs();
    return logs.filter(log => log.timestamp > timestamp);
  }

  // Add methods for individual entities
  static async addEmployee(employee: Employee): Promise<void> {
    const result = await CSVAppendManager.appendToCSV('employees', employee);
    if (result.success) {
      this.logTransaction('employee', 'create', employee);
    } else {
      console.error('Failed to add employee:', result.error);
      throw new Error(result.message);
    }
  }

  static getEmployees(): Employee[] {
    return this.loadEmployees();
  }

  static async addEquipment(equipment: Equipment): Promise<void> {
    const result = await CSVAppendManager.appendToCSV('equipment', equipment);
    if (result.success) {
      this.logTransaction('equipment', 'create', equipment);
    } else {
      console.error('Failed to add equipment:', result.error);
      throw new Error(result.message);
    }
  }

  static getEquipment(): Equipment[] {
    return this.loadEquipment();
  }

  static async addMaterial(material: Material): Promise<void> {
    const result = await CSVAppendManager.appendToCSV('materials', material);
    if (result.success) {
      this.logTransaction('material', 'create', material);
    } else {
      console.error('Failed to add material:', result.error);
      throw new Error(result.message);
    }
  }

  static getMaterials(): Material[] {
    return this.loadMaterials();
  }

  static async addSite(site: Site): Promise<void> {
    const result = await CSVAppendManager.appendToCSV('sites', site);
    if (result.success) {
      this.logTransaction('site', 'create', site);
    } else {
      console.error('Failed to add site:', result.error);
      throw new Error(result.message);
    }
  }

  static getSites(): Site[] {
    return this.loadSites();
  }

  // Bulk append methods using the new CSV append functionality
  static bulkAddEmployees(employees: Employee[]): { success: boolean; message: string; errors: string[] } {
    const errors: string[] = [];
    let successCount = 0;

    for (const employee of employees) {
      try {
        this.addEmployee(employee);
        successCount++;
      } catch (error) {
        errors.push(`Employee ${employee.id}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }

    return {
      success: errors.length === 0,
      message: `Successfully added ${successCount}/${employees.length} employees`,
      errors
    };
  }

  static bulkAddEquipment(equipment: Equipment[]): { success: boolean; message: string; errors: string[] } {
    const errors: string[] = [];
    let successCount = 0;

    for (const eq of equipment) {
      try {
        this.addEquipment(eq);
        successCount++;
      } catch (error) {
        errors.push(`Equipment ${eq.id}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }

    return {
      success: errors.length === 0,
      message: `Successfully added ${successCount}/${equipment.length} equipment items`,
      errors
    };
  }

  static bulkAddMaterials(materials: Material[]): { success: boolean; message: string; errors: string[] } {
    const errors: string[] = [];
    let successCount = 0;

    for (const material of materials) {
      try {
        this.addMaterial(material);
        successCount++;
      } catch (error) {
        errors.push(`Material ${material.id}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }

    return {
      success: errors.length === 0,
      message: `Successfully added ${successCount}/${materials.length} materials`,
      errors
    };
  }

  static bulkAddSites(sites: Site[]): { success: boolean; message: string; errors: string[] } {
    const errors: string[] = [];
    let successCount = 0;

    for (const site of sites) {
      try {
        this.addSite(site);
        successCount++;
      } catch (error) {
        errors.push(`Site ${site.id}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }

    return {
      success: errors.length === 0,
      message: `Successfully added ${successCount}/${sites.length} sites`,
      errors
    };
  }

  // Initialize default admin user
  static initializeDefaultAdmin(): void {
    const users = this.loadUsers();
    console.log('Current users before admin check:', users);
    
    // Check for both admin and developer users
    const adminExists = users.some(user => user.username === 'admin');
    const developerExists = users.some(user => user.username === 'developer');
    
    console.log('Admin exists check:', adminExists);
    console.log('Developer exists check:', developerExists);
    
    // Create developer user (highest access level)
    if (!developerExists) {
      const defaultDeveloper: User = {
        id: 'developer-001',
        username: 'developer',
        password: 'Umar123$',
        role: 'developer',
        name: 'System Developer',
        email: 'developer@qrsystem.com',
        isFirstLogin: false,
        createdAt: new Date().toISOString()
      };
      
      users.push(defaultDeveloper);
      console.log('Default developer user created:', defaultDeveloper);
    }
    
    // Create admin user
    if (!adminExists) {
      const defaultAdmin: User = {
        id: 'admin-001',
        username: 'admin',
        password: 'admin123',
        role: 'admin',
        name: 'System Administrator',
        email: 'admin@qrsystem.com',
        isFirstLogin: false,
        createdAt: new Date().toISOString()
      };
      
      users.push(defaultAdmin);
      this.saveUsers(users);
      console.log('Default admin user created:', defaultAdmin);
    }
    
    // Save updated users
    if (!adminExists || !developerExists) {
      this.saveUsers(users);
      console.log('Users after creation:', this.loadUsers());
    }
  }

  // Clear all data
  static clearAllData(): void {
    Object.values(this.STORAGE_KEYS).forEach(key => {
      localStorage.removeItem(key);
    });
  }

  // Maintenance Material Request Storage
  static saveMaintenanceMaterialRequests(requests: any[]): void {
    try {
      localStorage.setItem(DataStorage.STORAGE_KEYS.maintenanceMaterialRequests, JSON.stringify(requests));
    } catch (error) {
      console.error('Error saving maintenance material requests:', error);
    }
  }

  static loadMaintenanceMaterialRequests(): any[] {
    try {
      const data = localStorage.getItem(DataStorage.STORAGE_KEYS.maintenanceMaterialRequests);
      return data ? JSON.parse(data) : [];
    } catch (error) {
      console.error('Error loading maintenance material requests:', error);
      return [];
    }
  }

  static saveMaintenanceMaterialRequestItems(items: any[]): void {
    try {
      localStorage.setItem(DataStorage.STORAGE_KEYS.maintenanceMaterialRequestItems, JSON.stringify(items));
    } catch (error) {
      console.error('Error saving maintenance material request items:', error);
    }
  }

  static loadMaintenanceMaterialRequestItems(): any[] {
    try {
      const data = localStorage.getItem(DataStorage.STORAGE_KEYS.maintenanceMaterialRequestItems);
      return data ? JSON.parse(data) : [];
    } catch (error) {
      console.error('Error loading maintenance material request items:', error);
      return [];
    }
  }
}